version: '3.7'

services:
  pupetteer2:
    image: pupetteer2
    build: .
    volumes :
      - "./accounts:/accounts"
      - "./env:/env"
    command: "npm start"
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000